apiVersion: v1
kind: Pod
metadata:
  labels:
    run: spark-app-pi
  name: spark-app-pi
  namespace: default
spec:
  # Required to be able to run pods
  serviceAccount: spark
  containers:
  - args:
    - driver
    - --master
    - k8s://https://kubernetes.default:443
    - --name
    - spark-pi
    - --conf
    - spark.executor.instances=8
    - --class
    - org.apache.spark.examples.SparkPi
    - --conf
    - spark.kubernetes.authenticate.driver.serviceAccountName=spark
    - --conf
    - spark.kubernetes.executor.request.cores=1
    # Kube specific conf
    - --conf
    - spark.kubernetes.executor.podTemplateFile=/etc/config/executor.yaml
      # REPLACED by Pod template
      #- --conf
      #- spark.kubernetes.container.image=ryaxtech/spark-on-k8s:v0.1.0
    - --conf
    - spark.driver.host=spark-app-pi
    - --conf
    - spark.driver.port=4041
    - --conf
    - spark.driver.bindAddress=0.0.0.0
    - --conf
    - spark.eventLog.enabled=true
    - --conf
    - spark.eventLog.dir=/data
    - --conf
    - spark.kubernetes.driver.volumes.nfs.images.options.server=server
    - --conf
    - spark.kubernetes.driver.volumes.nfs.images.options.path=/data
    - local:///usr/local/spark/examples/jars/spark-examples_2.11-2.4.5.jar
    - "50000"
    image: ryaxtech/spark-on-k8s:v0.1.0
    imagePullPolicy: IfNotPresent
    name: spark-driver-1
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  restartPolicy: Never
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: pod-templates
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-templates
data:
  executor.yaml: |
    spec:
      tolerations:
      - key: "bebida"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - image: ryaxtech/spark-on-k8s:v0.1.0
---
apiVersion: v1
kind: Service
metadata:
  name: spark-app-pi
spec:
  clusterIP: None
  selector:
    run: spark-app-pi
  ports:
    - protocol: TCP
      port: 4041
      targetPort: 4041

