apiVersion: v1
kind: Pod
metadata:
  labels:
    run: spark-app-pi
  name: spark-app-pi
  namespace: default
spec:
  containers:
  - args:
    - driver
    - --master
    - k8s://https://kubernetes.default:443
    - --deploy-mode
    - cluster
    - --name
    - spark-pi
    - --conf
    - spark.executor.instances=8
    - --conf
    - spark.kubernetes.container.image=ryaxtech/spark-on-k8s:v0.1.0
    - --class
    - org.apache.spark.examples.SparkPi
    #- --conf
    #- spark.kubernetes.authenticate.driver.serviceAccountName=spark
      #- --conf
      #- spark.kubernetes.node.selector.runtime=singularity
    - --conf
    - spark.kubernetes.executor.request.cores=1
   # - --conf
   # - spark.kubernetes.driver.pod.name=spark-app-pi
    #- --conf
    #- spark.driver.host=spark-app-pi
    #- --conf
    #- spark.driver.port=4041
    #- --conf
    #- spark.driver.bindAddress=0.0.0.0
    - --conf
    - spark.eventLog.enabled=true
    - --conf
    - spark.eventLog.dir=/data/results
    #- --conf
    #- spark.kubernetes.driver.volumes.hostPath.resultdir.options.type=Directory
    #- --conf
    #- spark.kubernetes.driver.volumes.hostPath.resultdir.options.path=/home/mimercier/data/
    #- --conf
    #- spark.kubernetes.driver.volumes.hostPath.resultdir.mount.path=/data/results
    - local:///usr/local/spark/examples/jars/spark-examples_2.11-2.4.5.jar
    - "20000"
    image: ryaxtech/spark-on-k8s:v0.1.0
    imagePullPolicy: IfNotPresent
    name: spark-driver-1
    resources: {}
    volumeMounts:
    - mountPath: /data/results
      name: result-dir
  volumes:
  - name: result-dir
    hostPath:
      path: /home/mimercier/data # directory location on host
      type: Directory # this field is optional
  nodeSelector:
    kubernetes.io/hostname: server # WARNING: CHANGE THIS Select any not HPC node
  restartPolicy: Never
  serviceAccount: spark
---
apiVersion: v1
kind: Service
metadata:
  name: spark-app-pi
spec:
  clusterIP: None
  selector:
    run: spark-app-pi
  ports:
    - protocol: TCP
      port: 4041
      targetPort: 4041

